name: clockwork_gregorian_calendar
description: Gregorian calendar support for the clockwork library.

version: 0.0.1

environment:
  sdk: '>2.7.0 <3.0.0'

dependencies:
  clockwork:
    path: ../clockwork